"""
Test configuration and fixtures for library service tests.
"""
import pytest
import asyncio
from unittest.mock import patch
from uuid import uuid4

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))


# ========================================
# FAKE REDIS FOR TESTING
# ========================================

class FakeRedis:
    """
    Fake Redis client for testing to avoid event loop issues.
    Implements the Redis interface used by the app without actual connections.
    """
    def __init__(self):
        self.kv_store = {}
        self.hash_store = {}

    async def hgetall(self, key):
        return self.hash_store.get(key, {})

    async def hset(self, key, mapping):
        self.hash_store.setdefault(key, {}).update({k: str(v) for k, v in mapping.items()})

    async def expire(self, key, seconds):
        return True

    async def set(self, key, value, ex=None):
        self.kv_store[key] = value
        return True

    async def get(self, key):
        return self.kv_store.get(key)

    async def delete(self, *keys):
        for key in keys:
            self.kv_store.pop(key, None)
        return len(keys)

    async def exists(self, key):
        return 1 if key in self.kv_store else 0

    async def keys(self, pattern):
        """Simple pattern matching for test: prefix."""
        if pattern.endswith("*"):
            prefix = pattern[:-1]
            return [k for k in self.kv_store.keys() if k.startswith(prefix)]
        return [k for k in self.kv_store.keys() if k == pattern]

    async def incr(self, key):
        """Increment a key."""
        current = self.kv_store.get(key, "0")
        new_val = int(current) + 1
        self.kv_store[key] = str(new_val)
        return new_val

    async def aclose(self):
        """Close connection (no-op for fake)."""
        pass

    def pipeline(self):
        return _FakePipeline(self)


class _FakePipeline:
    """Fake Redis pipeline for testing."""
    def __init__(self, redis_client: FakeRedis):
        self.redis = redis_client
        self.ops = []

    def get(self, key):
        self.ops.append(("get", key))
        return self

    def delete(self, key):
        self.ops.append(("delete", key))
        return self

    async def execute(self):
        results = []
        for op, key in self.ops:
            if op == "get":
                results.append(await self.redis.get(key))
            elif op == "delete":
                await self.redis.delete(key)
                results.append(1)
        return results

from httpx import AsyncClient, ASGITransport
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.pool import NullPool

import main
from database import get_async_db, Base
from models import ContentStatus

app = main.app


# ========================================
# DATABASE FIXTURES
# ========================================

# Import settings for real database URL
from settings import settings

# Use real PostgreSQL database for testing
TEST_DATABASE_URL = settings.DATABASE_ASYNC_URL


# Note: event_loop fixture removed as pytest-asyncio handles it automatically
# If you need custom event loop config, use pytest-asyncio's scope parameter


@pytest.fixture(scope="function")
async def db():
    """
    Create a test database session using the real PostgreSQL database.
    Uses a transaction that is rolled back after each test.
    """
    # Create engine
    engine = create_async_engine(TEST_DATABASE_URL, echo=False)
    
    # Create session factory
    async_session_maker = async_sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )
    
    async with async_session_maker() as session:
        # Start a transaction
        async with session.begin():
            yield session
            # Rollback after test
            await session.rollback()
    
    await engine.dispose()


@pytest.fixture
async def client(db: AsyncSession):
    """Create an async test client with overridden database dependency."""
    
    async def override_get_db():
        yield db
    
    app.dependency_overrides[get_async_db] = override_get_db
    
    async with AsyncClient(
        transport=ASGITransport(app=app),
        base_url="http://test"
    ) as ac:
        yield ac
    
    app.dependency_overrides.clear()


@pytest.fixture
async def async_client(test_db: AsyncSession):
    """
    Create an async test client with proper auth mocking.
    Supports test JWT tokens generated by helpers.jwt_utils.create_test_jwt().
    Uses RS256 algorithm to match production.
    """
    from helpers.jwt_utils import TEST_JWT_PUBLIC_KEY, TEST_JWT_ALGORITHM
    from dependencies.auth import get_current_user
    import jwt as pyjwt
    from uuid import UUID
    
    async def override_get_db():
        yield test_db
    
    from fastapi import Header
    from fastapi.security import HTTPBearer
    
    security = HTTPBearer()
    
    async def mock_get_current_user(authorization: str = Header(None)) -> dict:
        """Mock authentication to decode test JWTs from Authorization header."""
        if not authorization or not authorization.startswith("Bearer "):
            from fastapi import HTTPException, status
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Missing or invalid authorization header",
            )
        
        token = authorization.replace("Bearer ", "")
        
        try:
            # Decode using RS256 with public key (matches production)
            payload = pyjwt.decode(
                token, 
                TEST_JWT_PUBLIC_KEY, 
                algorithms=[TEST_JWT_ALGORITHM],
                audience=settings.JWT_AUDIENCE,
                issuer=settings.JWT_ISSUER,
            )
            # Convert user_id string back to UUID if it's a string
            if "user_id" in payload and isinstance(payload["user_id"], str):
                payload["user_id"] = UUID(payload["user_id"])
            return payload
        except pyjwt.InvalidTokenError as e:
            from fastapi import HTTPException, status
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail=f"Invalid token: {str(e)}",
            )
    
    # Create FakeRedis for this test session
    fake_redis = FakeRedis()
    
    async def override_get_redis():
        """Override Redis dependency to return FakeRedis."""
        return fake_redis
    
    # Import cache module's get_redis to override it
    from cache import get_redis
    
    # Override database and all auth dependencies
    app.dependency_overrides[get_async_db] = override_get_db
    app.dependency_overrides[get_current_user] = mock_get_current_user
    app.dependency_overrides[get_redis] = override_get_redis
    
    try:
        async with AsyncClient(
            transport=ASGITransport(app=app),
            base_url="http://test"
        ) as ac:
            yield ac
    finally:
        app.dependency_overrides.clear()


@pytest.fixture
async def test_db():
    """
    Create a test database session with transaction rollback.
    Mocks commit() as flush() to prevent "closed transaction" errors.
    """
    # Create engine
    engine = create_async_engine(TEST_DATABASE_URL, echo=False)
    
    # Create session factory
    async_session_maker = async_sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )
    
    async with async_session_maker() as session:
        # Start a transaction
        async with session.begin():
            # Mock commit to be flush - prevents "closed transaction" errors
            # This allows code to call commit() in tests without breaking the transaction
            original_commit = session.commit
            session.commit = session.flush
            
            yield session
            
            # Restore original commit and rollback
            session.commit = original_commit
            await session.rollback()
    
    await engine.dispose()


# ========================================
# AUTH FIXTURES
# ========================================

@pytest.fixture
def mock_jwt_user():
    """Mock JWT user with standard scopes."""
    user_data = {
        "user_id": uuid4(),
        "username": "testuser",
        "email": "test@example.com",
        "scopes": ["content:submit", "content:edit_any"],
        "roles": ["contributor"],
        "trust_score": 50,
    }
    
    # Patch all auth dependencies
    with patch("dependencies.auth.get_current_user", return_value=user_data), \
         patch("dependencies.auth.require_scope", return_value=user_data), \
         patch("dependencies.auth.require_role", return_value=user_data), \
         patch("dependencies.auth.require_min_trust", return_value=user_data):
        yield user_data


@pytest.fixture
def mock_admin_user():
    """Mock JWT user with admin role."""
    user_data = {
        "user_id": uuid4(),
        "username": "adminuser",
        "email": "admin@example.com",
        "scopes": ["content:submit", "content:edit_any", "content:delete_any"],
        "roles": ["admin"],
        "trust_score": 100,
    }
    
    # Patch all auth dependencies
    with patch("dependencies.auth.get_current_user", return_value=user_data), \
         patch("dependencies.auth.require_scope", return_value=user_data), \
         patch("dependencies.auth.require_role", return_value=user_data), \
         patch("dependencies.auth.require_min_trust", return_value=user_data):
        yield user_data


# ========================================
# REDIS FIXTURES
# ========================================

@pytest.fixture(scope="function")
async def redis():
    """
    Create a fresh FakeRedis instance for each test.
    This avoids event loop issues with real Redis connections.
    """
    fake_redis = FakeRedis()
    yield fake_redis
    # Cleanup is automatic since it's just a dict in memory


# ========================================
# BOOK & REVIEW FIXTURES (Phase 3)
# ========================================

@pytest.fixture
async def approved_author(test_db):
    """Create an approved, public author for book tests."""
    from models import Author, ContentStatus
    
    author = Author(
        name="Test Author",
        email="author@example.com",
        bio="Test bio",
        created_by_user_id=uuid4(),
        status=ContentStatus.APPROVED,
        is_public=True,
        version=1,
    )
    test_db.add(author)
    await test_db.commit()
    await test_db.refresh(author)
    return author


@pytest.fixture
async def pending_book(test_db, approved_author):
    """Create a pending book for approval tests."""
    from models import Book, ContentStatus
    
    book = Book(
        title="Pending Test Book",
        year=2023,
        description="Test description",
        tags=["test", "pending"],
        created_by_user_id=uuid4(),
        status=ContentStatus.PENDING,
        is_public=False,
        version=1,
    )
    book.authors = [approved_author]
    test_db.add(book)
    await test_db.commit()
    await test_db.refresh(book)
    return book


@pytest.fixture
async def approved_book(test_db, approved_author):
    """Create an approved, public book for testing."""
    from models import Book, ContentStatus
    
    book = Book(
        title="Approved Test Book",
        year=2023,
        description="Test description",
        created_by_user_id=uuid4(),
        status=ContentStatus.APPROVED,
        is_public=True,
        version=1,
    )
    book.authors = [approved_author]
    test_db.add(book)
    await test_db.commit()
    await test_db.refresh(book)
    return book


@pytest.fixture
async def rejected_book(test_db, approved_author):
    """Create a rejected book for testing."""
    from models import Book, ContentStatus
    
    book = Book(
        title="Rejected Test Book",
        year=2023,
        created_by_user_id=uuid4(),
        status=ContentStatus.REJECTED,
        is_public=False,
        version=1,
    )
    book.authors = [approved_author]
    test_db.add(book)
    await test_db.commit()
    await test_db.refresh(book)
    return book


@pytest.fixture
async def deleted_book(test_db, approved_author):
    """Create a soft-deleted book for recovery tests."""
    from models import Book, ContentStatus
    from datetime import datetime, timezone
    
    book = Book(
        title="Deleted Test Book",
        year=2023,
        created_by_user_id=uuid4(),
        status=ContentStatus.APPROVED,
        is_public=False,
        is_deleted=True,
        deleted_at=datetime.now(timezone.utc),
        version=1,
    )
    book.authors = [approved_author]
    test_db.add(book)
    await test_db.commit()
    await test_db.refresh(book)
    return book


@pytest.fixture
def regular_user():
    """Regular user with basic permissions."""
    return {
        "user_id": str(uuid4()),
        "scopes": ["books:draft", "books:update_own", "reviews:create"],
        "trust_score": 5,
    }


@pytest.fixture
def curator_user():
    """Curator user with override permissions."""
    return {
        "user_id": str(uuid4()),
        "scopes": ["jury:override", "content:takedown"],
        "trust_score": 85,
        "reputation": 95,
    }


@pytest.fixture
def subscribed_user():
    """User for subscription tests."""
    return {
        "user_id": str(uuid4()),
        "scopes": ["books:read"],
        "trust_score": 10,
    }
