"""
Test configuration and fixtures for library service tests.
"""
import pytest
import asyncio
from unittest.mock import patch
from uuid import uuid4

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from httpx import AsyncClient, ASGITransport
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.pool import NullPool

import main
from database import get_async_db, Base
from models import ContentStatus

app = main.app


# ========================================
# DATABASE FIXTURES
# ========================================

# Import settings for real database URL
from settings import settings

# Use real PostgreSQL database for testing
TEST_DATABASE_URL = settings.DATABASE_ASYNC_URL


# Note: event_loop fixture removed as pytest-asyncio handles it automatically
# If you need custom event loop config, use pytest-asyncio's scope parameter


@pytest.fixture(scope="function")
async def db():
    """
    Create a test database session using the real PostgreSQL database.
    Uses a transaction that is rolled back after each test.
    """
    # Create engine
    engine = create_async_engine(TEST_DATABASE_URL, echo=False)
    
    # Create session factory
    async_session_maker = async_sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )
    
    async with async_session_maker() as session:
        # Start a transaction
        async with session.begin():
            yield session
            # Rollback after test
            await session.rollback()
    
    await engine.dispose()


@pytest.fixture
async def client(db: AsyncSession):
    """Create an async test client with overridden database dependency."""
    
    async def override_get_db():
        yield db
    
    app.dependency_overrides[get_async_db] = override_get_db
    
    async with AsyncClient(
        transport=ASGITransport(app=app),
        base_url="http://test"
    ) as ac:
        yield ac
    
    app.dependency_overrides.clear()


@pytest.fixture
async def async_client(test_db: AsyncSession):
    """
    Create an async test client with proper auth mocking.
    Supports test JWT tokens generated by helpers.jwt_utils.create_test_jwt().
    Uses RS256 algorithm to match production.
    """
    from helpers.jwt_utils import TEST_JWT_PUBLIC_KEY, TEST_JWT_ALGORITHM
    from dependencies.auth import get_current_user
    import jwt as pyjwt
    from uuid import UUID
    
    async def override_get_db():
        yield test_db
    
    from fastapi import Header
    from fastapi.security import HTTPBearer
    
    security = HTTPBearer()
    
    async def mock_get_current_user(authorization: str = Header(None)) -> dict:
        """Mock authentication to decode test JWTs from Authorization header."""
        if not authorization or not authorization.startswith("Bearer "):
            from fastapi import HTTPException, status
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Missing or invalid authorization header",
            )
        
        token = authorization.replace("Bearer ", "")
        
        try:
            # Decode using RS256 with public key (matches production)
            payload = pyjwt.decode(
                token, 
                TEST_JWT_PUBLIC_KEY, 
                algorithms=[TEST_JWT_ALGORITHM],
                audience=settings.JWT_AUDIENCE,
                issuer=settings.JWT_ISSUER,
            )
            # Convert user_id string back to UUID if it's a string
            if "user_id" in payload and isinstance(payload["user_id"], str):
                payload["user_id"] = UUID(payload["user_id"])
            return payload
        except pyjwt.InvalidTokenError as e:
            from fastapi import HTTPException, status
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail=f"Invalid token: {str(e)}",
            )
    
    # Override database and all auth dependencies
    app.dependency_overrides[get_async_db] = override_get_db
    app.dependency_overrides[get_current_user] = mock_get_current_user
    
    try:
        async with AsyncClient(
            transport=ASGITransport(app=app),
            base_url="http://test"
        ) as ac:
            yield ac
    finally:
        app.dependency_overrides.clear()


@pytest.fixture
async def test_db():
    """
    Create a test database session with transaction rollback.
    Mocks commit() as flush() to prevent "closed transaction" errors.
    """
    # Create engine
    engine = create_async_engine(TEST_DATABASE_URL, echo=False)
    
    # Create session factory
    async_session_maker = async_sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )
    
    async with async_session_maker() as session:
        # Start a transaction
        async with session.begin():
            # Mock commit to be flush - prevents "closed transaction" errors
            # This allows code to call commit() in tests without breaking the transaction
            original_commit = session.commit
            session.commit = session.flush
            
            yield session
            
            # Restore original commit and rollback
            session.commit = original_commit
            await session.rollback()
    
    await engine.dispose()


# ========================================
# AUTH FIXTURES
# ========================================

@pytest.fixture
def mock_jwt_user():
    """Mock JWT user with standard scopes."""
    user_data = {
        "user_id": uuid4(),
        "username": "testuser",
        "email": "test@example.com",
        "scopes": ["content:submit", "content:edit_any"],
        "roles": ["contributor"],
        "trust_score": 50,
    }
    
    # Patch all auth dependencies
    with patch("dependencies.auth.get_current_user", return_value=user_data), \
         patch("dependencies.auth.require_scope", return_value=user_data), \
         patch("dependencies.auth.require_role", return_value=user_data), \
         patch("dependencies.auth.require_min_trust", return_value=user_data):
        yield user_data


@pytest.fixture
def mock_admin_user():
    """Mock JWT user with admin role."""
    user_data = {
        "user_id": uuid4(),
        "username": "adminuser",
        "email": "admin@example.com",
        "scopes": ["content:submit", "content:edit_any", "content:delete_any"],
        "roles": ["admin"],
        "trust_score": 100,
    }
    
    # Patch all auth dependencies
    with patch("dependencies.auth.get_current_user", return_value=user_data), \
         patch("dependencies.auth.require_scope", return_value=user_data), \
         patch("dependencies.auth.require_role", return_value=user_data), \
         patch("dependencies.auth.require_min_trust", return_value=user_data):
        yield user_data
