"""drop unused table

Revision ID: 2bf3c284c1ef
Revises: a32242427cd7
Create Date: 2025-12-24 22:20:20.550368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf3c284c1ef'
down_revision: Union[str, Sequence[str], None] = 'a32242427cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_uploads_expires_at'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_status_expires'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_user_status'), table_name='pending_uploads')
    op.drop_table('pending_uploads')
    op.create_index(op.f('ix_authors_created_at'), 'authors', ['created_at'], unique=False)
    op.create_index(op.f('ix_books_created_at'), 'books', ['created_at'], unique=False)
    op.create_index(op.f('ix_collections_created_at'), 'collections', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_created_at'), table_name='collections')
    op.drop_index(op.f('ix_books_created_at'), table_name='books')
    op.drop_index(op.f('ix_authors_created_at'), table_name='authors')
    op.create_table('pending_uploads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('upload_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'REVOKED', name='upload_status'), server_default=sa.text("'PENDING'::upload_status"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP + '00:10:00'::interval)"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_uploads_pkey'))
    )
    op.create_index(op.f('ix_pending_uploads_user_status'), 'pending_uploads', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_pending_uploads_status_expires'), 'pending_uploads', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_pending_uploads_expires_at'), 'pending_uploads', ['expires_at'], unique=False)
    # ### end Alembic commands ###
