"""add_constraints_indexes_and_change_tags_to_array

Revision ID: 3c42c83764b2
Revises: a9a7909268a2
Create Date: 2025-12-15 22:29:58.814523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c42c83764b2'
down_revision: Union[str, Sequence[str], None] = 'a9a7909268a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Keeping trigram indexes (idx_authors_name_trgm, idx_authors_email_trgm, idx_books_title_trgm)
    # and FTS index (ix_books_search_tsv) from previous migration
    op.create_index('ix_authors_linked_user', 'authors', ['linked_user_id'], unique=False)
    
    # Multi-step conversion: JSONB → ARRAY (PostgreSQL doesn't allow subqueries in USING clause)
    # Step 1: Add temporary array column
    op.add_column('books', sa.Column('tags_new', postgresql.ARRAY(sa.String()), nullable=True))
    
    # Step 2: Migrate data - extract JSONB values into array
    op.execute("""
        UPDATE books 
        SET tags_new = CASE 
            WHEN tags IS NULL THEN NULL
            WHEN jsonb_typeof(tags) = 'object' THEN ARRAY(SELECT jsonb_array_elements_text(jsonb_agg(value)) FROM jsonb_each_text(tags))
            ELSE NULL
        END
    """)
    
    # Step 3: Drop old JSONB column and its GIN index
    op.drop_index('ix_books_tags_gin', table_name='books', postgresql_using='gin')
    op.drop_column('books', 'tags')
    
    # Step 4: Rename new column to 'tags'
    op.alter_column('books', 'tags_new', new_column_name='tags')
    
    # Step 5: Recreate GIN index on new ARRAY column
    op.create_index('ix_books_tags_gin', 'books', ['tags'], postgresql_using='gin')
    
    op.create_index('ix_books_file_format', 'books', ['file_format'], unique=False)
    op.create_index('ix_collection_books_book', 'collection_books', ['book_id'], unique=False)
    op.create_unique_constraint('uq_collection_books_position', 'collection_books', ['collection_id', 'position'])
    op.drop_index(op.f('ix_edit_history_entity'), table_name='edit_history')
    op.create_index('ix_edit_history_entity', 'edit_history', ['entity_type', 'entity_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_edit_history_entity_version', 'edit_history', ['entity_type', 'entity_id', 'version'], unique=True)
    op.create_index('ix_pending_uploads_status_expires', 'pending_uploads', ['status', 'expires_at'], unique=False)
    op.create_index('ix_reviews_book_helpful', 'reviews', ['book_id', 'helpful_count'], unique=False)
    op.create_index('ix_reviews_book_rating', 'reviews', ['book_id', 'rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_book_rating', table_name='reviews')
    op.drop_index('ix_reviews_book_helpful', table_name='reviews')
    op.drop_index('ix_pending_uploads_status_expires', table_name='pending_uploads')
    op.drop_index('ix_edit_history_entity_version', table_name='edit_history')
    op.drop_index('ix_edit_history_entity', table_name='edit_history', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_edit_history_entity'), 'edit_history', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint('uq_collection_books_position', 'collection_books', type_='unique')
    op.drop_index('ix_collection_books_book', table_name='collection_books')
    op.drop_index('ix_books_file_format', table_name='books')
    # NOTE: Not recreating trigram/FTS indexes since they weren't dropped in upgrade
    
    # Multi-step conversion: ARRAY → JSONB
    # Step 1: Add temporary JSONB column
    op.add_column('books', sa.Column('tags_new', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Step 2: Migrate data - convert array back to JSONB object with indexed keys
    op.execute("""
        UPDATE books 
        SET tags_new = CASE 
            WHEN tags IS NULL THEN NULL
            WHEN array_length(tags, 1) IS NULL THEN NULL
            ELSE (SELECT jsonb_object_agg('tag' || idx::text, val) 
                  FROM unnest(tags) WITH ORDINALITY AS t(val, idx))
        END
    """)
    
    # Step 3: Drop old ARRAY column and its GIN index
    op.drop_index('ix_books_tags_gin', table_name='books', postgresql_using='gin')
    op.drop_column('books', 'tags')
    
    # Step 4: Rename new column to 'tags'
    op.alter_column('books', 'tags_new', new_column_name='tags')
    
    # Step 5: Recreate GIN index on JSONB column
    op.create_index('ix_books_tags_gin', 'books', ['tags'], postgresql_using='gin')
    
    op.drop_index('ix_authors_linked_user', table_name='authors')
    # ### end Alembic commands ###
