"""update statistic columns for books

Revision ID: 59f75d6759cb
Revises: b164bcb064bf
Create Date: 2025-12-23 20:19:49.904041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f75d6759cb'
down_revision: Union[str, Sequence[str], None] = 'b164bcb064bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('average_rating', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('books', sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('books', sa.Column('trending_score', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.create_index('ix_books_average_rating', 'books', ['average_rating'], unique=False, postgresql_where='average_rating > 0 and is_public = true and is_deleted = false')
    op.create_index('ix_books_subscriber_count', 'books', ['subscriber_count'], unique=False, postgresql_where='subscriber_count > 0 and is_public = true and is_deleted = false')
    op.create_index('ix_books_trending_score', 'books', ['trending_score'], unique=False, postgresql_where='trending_score > 0 and is_public = true and is_deleted = false')
    op.create_index('ix_books_view_count', 'books', ['view_count'], unique=False, postgresql_where='view_count > 0 and is_public = true and is_deleted = false')
    op.drop_index(op.f('ix_edit_history_entity'), table_name='edit_history')
    op.create_index('ix_edit_history_entity', 'edit_history', ['entity_type', 'entity_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edit_history_entity', table_name='edit_history', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_edit_history_entity'), 'edit_history', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_books_view_count', table_name='books', postgresql_where='view_count > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_books_trending_score', table_name='books', postgresql_where='trending_score > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_books_subscriber_count', table_name='books', postgresql_where='subscriber_count > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_books_average_rating', table_name='books', postgresql_where='average_rating > 0 and is_public = true and is_deleted = false')
    op.drop_column('books', 'trending_score')
    op.drop_column('books', 'view_count')
    op.drop_column('books', 'average_rating')
    # ### end Alembic commands ###
