"""update the tables to support collection endpoints

Revision ID: a32242427cd7
Revises: 59f75d6759cb
Create Date: 2025-12-24 01:04:07.026600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a32242427cd7'
down_revision: Union[str, Sequence[str], None] = '59f75d6759cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'C')", persisted=True), nullable=False))
    op.add_column('collections', sa.Column('book_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('collections', sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('collections', sa.Column('trending_score', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.create_index('ix_collections_name_trgm', 'collections', [sa.literal_column('immutable_unaccent(name)')], unique=False, postgresql_ops={'immutable_unaccent(name)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('ix_collections_search_tsv', 'collections', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_collections_subscriber_count', 'collections', ['subscriber_count'], unique=False, postgresql_where='subscriber_count > 0 and is_public = true and is_deleted = false')
    op.create_index('ix_collections_trending_score', 'collections', ['trending_score'], unique=False, postgresql_where='trending_score > 0 and is_public = true and is_deleted = false')
    op.create_index('ix_collections_view_count', 'collections', ['view_count'], unique=False, postgresql_where='view_count > 0 and is_public = true and is_deleted = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collections_view_count', table_name='collections', postgresql_where='view_count > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_collections_trending_score', table_name='collections', postgresql_where='trending_score > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_collections_subscriber_count', table_name='collections', postgresql_where='subscriber_count > 0 and is_public = true and is_deleted = false')
    op.drop_index('ix_collections_search_tsv', table_name='collections', postgresql_using='gin')
    op.drop_index('ix_collections_name_trgm', table_name='collections', postgresql_ops={'immutable_unaccent(name)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('collections', 'trending_score')
    op.drop_column('collections', 'view_count')
    op.drop_column('collections', 'book_count')
    op.drop_column('collections', 'search_tsv')
    # ### end Alembic commands ###
