"""complete_schema_redesign

Revision ID: a9a7909268a2
Revises: 
Create Date: 2025-12-15 17:17:00.410148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9a7909268a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ===== MANUALLY ADDED: PostgreSQL Extensions =====
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    
    # ===== MANUALLY ADDED: Immutable unaccent function for functional indexes =====
    op.execute("""
        CREATE OR REPLACE FUNCTION immutable_unaccent(text)
        RETURNS text
        LANGUAGE sql
        IMMUTABLE
        AS $$
            SELECT public.unaccent($1);
        $$;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='content_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_edited_by', sa.UUID(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follower_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("email IS NULL OR email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='ck_authors_email_format'),
    sa.CheckConstraint('follower_count >= 0', name='ck_authors_follower_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authors_created_by', 'authors', ['created_by_user_id'], unique=False)
    op.create_index('ix_authors_deleted', 'authors', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index('ix_authors_status_public', 'authors', ['status', 'is_public'], unique=False)
    
    # ===== MANUALLY ADDED: GIN trigram indexes for Author similarity search =====
    op.create_index(
        "idx_authors_name_trgm",
        "authors",
        [sa.text("immutable_unaccent(name) gin_trgm_ops")],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_authors_email_trgm",
        "authors",
        [sa.text("immutable_unaccent(email) gin_trgm_ops")],
        postgresql_using="gin",
    )
    
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_key', sa.String(length=255), nullable=True),
    sa.Column('file_key', sa.String(length=255), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='content_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_edited_by', sa.UUID(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'C')", persisted=True), nullable=False),
    sa.CheckConstraint("file_format IS NULL OR file_format IN ('pdf', 'epub', 'mobi')", name='ck_books_file_format'),
    sa.CheckConstraint('subscriber_count >= 0', name='ck_books_subscriber_count_positive'),
    sa.CheckConstraint('year IS NULL OR year > 0', name='ck_books_year_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_created_by', 'books', ['created_by_user_id'], unique=False)
    op.create_index('ix_books_deleted', 'books', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index('ix_books_status_public', 'books', ['status', 'is_public'], unique=False)
    op.create_index('ix_books_tags_gin', 'books', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_books_year'), 'books', ['year'], unique=False)
    
    # ===== MANUALLY ADDED: GIN indexes for full-text search on Book =====
    op.create_index(
        "ix_books_search_tsv",
        "books",
        ["search_tsv"],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_books_title_trgm",
        "books",
        [sa.text("title gin_trgm_ops")],
        postgresql_using="gin",
    )
    
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='content_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_edited_by', sa.UUID(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('subscriber_count >= 0', name='ck_collections_subscriber_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collections_created_by', 'collections', ['created_by_user_id'], unique=False)
    op.create_index('ix_collections_deleted', 'collections', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index('ix_collections_status_public', 'collections', ['status', 'is_public'], unique=False)
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'RECOVER', name='edit_action'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_history_created_at'), 'edit_history', ['created_at'], unique=False)
    op.create_index('ix_edit_history_entity', 'edit_history', ['entity_type', 'entity_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_edit_history_id'), 'edit_history', ['id'], unique=False)
    op.create_index('ix_edit_history_user', 'edit_history', ['user_id', 'created_at'], unique=False)
    op.create_table('pending_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('upload_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REVOKED', name='upload_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '10 minutes'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_uploads_expires_at', 'pending_uploads', ['expires_at'], unique=False)
    op.create_index('ix_pending_uploads_user_status', 'pending_uploads', ['user_id', 'status'], unique=False)
    op.create_table('author_book_relation',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'book_id')
    )
    op.create_table('author_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'author_id')
    )
    op.create_index('ix_author_follows_author', 'author_follows', ['author_id', 'created_at'], unique=False)
    op.create_table('book_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.create_index('ix_book_subscriptions_book', 'book_subscriptions', ['book_id', 'created_at'], unique=False)
    op.create_table('collection_books',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_collection_books_position_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'book_id')
    )
    op.create_index('ix_collection_books_position', 'collection_books', ['collection_id', 'position'], unique=False)
    op.create_table('collection_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'collection_id')
    )
    op.create_index('ix_collection_subscriptions_collection', 'collection_subscriptions', ['collection_id', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unhelpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trust_awarded', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('helpful_count >= 0', name='ck_reviews_helpful_count_positive'),
    sa.CheckConstraint('rating > 0 AND rating <= 5', name='ck_reviews_rating_1_5'),
    sa.CheckConstraint('trust_awarded >= -5 AND trust_awarded <= 5', name='ck_reviews_trust_awarded_range'),
    sa.CheckConstraint('unhelpful_count >= 0', name='ck_reviews_unhelpful_count_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_reviews_book_user')
    )
    op.create_index('ix_reviews_deleted', 'reviews', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('review_votes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('HELPFUL', 'UNHELPFUL', name='vote_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'review_id')
    )
    op.create_index('ix_review_votes_review', 'review_votes', ['review_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ===== MANUALLY ADDED: Drop custom indexes first =====
    op.drop_index("idx_books_title_trgm", table_name="books", postgresql_using="gin")
    op.drop_index("ix_books_search_tsv", table_name="books", postgresql_using="gin")
    op.drop_index("idx_authors_email_trgm", table_name="authors", postgresql_using="gin")
    op.drop_index("idx_authors_name_trgm", table_name="authors", postgresql_using="gin")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_votes_review', table_name='review_votes')
    op.drop_table('review_votes')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('ix_reviews_deleted', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_collection_subscriptions_collection', table_name='collection_subscriptions')
    op.drop_table('collection_subscriptions')
    op.drop_index('ix_collection_books_position', table_name='collection_books')
    op.drop_table('collection_books')
    op.drop_index('ix_book_subscriptions_book', table_name='book_subscriptions')
    op.drop_table('book_subscriptions')
    op.drop_index('ix_author_follows_author', table_name='author_follows')
    op.drop_table('author_follows')
    op.drop_table('author_book_relation')
    op.drop_index('ix_pending_uploads_user_status', table_name='pending_uploads')
    op.drop_index('ix_pending_uploads_expires_at', table_name='pending_uploads')
    op.drop_table('pending_uploads')
    op.drop_index('ix_edit_history_user', table_name='edit_history')
    op.drop_index(op.f('ix_edit_history_id'), table_name='edit_history')
    op.drop_index('ix_edit_history_entity', table_name='edit_history', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_edit_history_created_at'), table_name='edit_history')
    op.drop_table('edit_history')
    op.drop_index('ix_collections_status_public', table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_index('ix_collections_deleted', table_name='collections')
    op.drop_index('ix_collections_created_by', table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_books_year'), table_name='books')
    op.drop_index('ix_books_tags_gin', table_name='books', postgresql_using='gin')
    op.drop_index('ix_books_status_public', table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index('ix_books_deleted', table_name='books')
    op.drop_index('ix_books_created_by', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_authors_status_public', table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index('ix_authors_deleted', table_name='authors')
    op.drop_index('ix_authors_created_by', table_name='authors')
    op.drop_table('authors')
    
    # ===== MANUALLY ADDED: Drop enum types =====
    op.execute("DROP TYPE IF EXISTS vote_type")
    op.execute("DROP TYPE IF EXISTS edit_action")
    op.execute("DROP TYPE IF EXISTS upload_status")
    op.execute("DROP TYPE IF EXISTS content_status")
    
    # ===== MANUALLY ADDED: Drop function and extensions =====
    op.execute("DROP FUNCTION IF EXISTS immutable_unaccent(text)")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS unaccent")
    # ### end Alembic commands ###
