"""add_jury_voting_system_all_entities

Revision ID: b164bcb064bf
Revises: 3c42c83764b2
Create Date: 2025-12-16 01:54:45.308283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b164bcb064bf'
down_revision: Union[str, Sequence[str], None] = '3c42c83764b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jury_votes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('vote_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("entity_type IN ('author', 'book', 'collection')", name='ck_jury_votes_valid_entity_type'),
    sa.CheckConstraint('vote_value IN (1, 5)', name='ck_jury_votes_valid_values'),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id')
    )
    op.create_index('ix_jury_votes_entity', 'jury_votes', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_jury_votes_user', 'jury_votes', ['user_id', 'created_at'], unique=False)
    op.add_column('authors', sa.Column('vote_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_check_constraint('ck_authors_vote_score_range', 'authors', 'vote_score >= 0 AND vote_score <= 5')
    op.add_column('books', sa.Column('vote_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_check_constraint('ck_books_vote_score_range', 'books', 'vote_score >= 0 AND vote_score <= 5')
    op.add_column('collections', sa.Column('vote_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_check_constraint('ck_collections_vote_score_range', 'collections', 'vote_score >= 0 AND vote_score <= 5')
    op.drop_index(op.f('ix_edit_history_entity'), table_name='edit_history')
    op.create_index('ix_edit_history_entity', 'edit_history', ['entity_type', 'entity_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edit_history_entity', table_name='edit_history', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_edit_history_entity'), 'edit_history', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint('ck_collections_vote_score_range', 'collections', type_='check')
    op.drop_column('collections', 'vote_score')
    op.drop_constraint('ck_books_vote_score_range', 'books', type_='check')
    op.drop_column('books', 'vote_score')
    op.drop_constraint('ck_authors_vote_score_range', 'authors', type_='check')
    op.drop_column('authors', 'vote_score')
    op.drop_index('ix_jury_votes_user', table_name='jury_votes')
    op.drop_index('ix_jury_votes_entity', table_name='jury_votes')
    op.drop_table('jury_votes')
    # ### end Alembic commands ###
